spring:
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: user
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: student
        format_sql: true

  rest:
    resttemplate:
      connect-timeout: 5000
      read-timeout: 5000

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: INFO
