spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: classes_route
          uri: http://class-service:8081
          predicates:
            - Path=/classes/**
        - id: teachers_route
          uri: http://teacher-service:8083
          predicates:
            - Path=/teachers/**
        - id: attendance_route
          uri: http://attendance-service:8082  # Ganti underscore dengan tanda hubung
          predicates:
            - Path=/attendance/**
        - id: student_route
          uri: http://student-service:8080
          predicates:
            - Path=/students/**
server:
  port: 9090
